import dlog 



def load_gb_file(file):
    bytes = None
    with open(file, "rb") as fh:    
        bytes = bytearray(fh.read())
    
    title = ""
    
    license = ""
    for i in range(0x0134, 0x0144):
        title += str(chr(bytes[i]))
    license_key = str(bytes[0x0144]&0xF)+str(bytes[0x0145]&0xF)
    license = license_map[license_key]
    
    cgb = bytes[0x0143]
    sgb = bytes[0x0146]
    
    carttype_key = bytes[0x0147]
    carttype = carttype_map[carttype_key]
    
    rom_size = rom_size_map[bytes[0x0148]]
    ram_size = ram_size_map[bytes[0x0149]]
    
    dlog.print_msg("CAR", "Title\t\t"+title)
    dlog.print_msg("CAR", "License\t\t"+license)
    dlog.print_msg("CAR", "SGB features\t"+str(sgb))
    dlog.print_msg("CAR", "Cartridge type\t"+carttype)
    dlog.print_msg("CAR", "ROM size\t"+str(rom_size)+"K")
    dlog.print_msg("CAR", "RAM size\t"+str(ram_size)+"K")

rom_size_map = [32, 64, 128, 256, 512, 1024, 2048, 4196]
ram_size_map = [0, 2, 8, 32]

carttype_map = [None]*0x100
carttype_map[0x00] = "ROM"
carttype_map[0x03] = "MBC1+RAM+BATTERY"
carttype_map[0x08] = "ROM+RAM"
carttype_map[0x0C] = "MMM01+RAM"
carttype_map[0x10] = "MBC3+TIMER+RAM+BATTERY"
carttype_map[0x13] = "MBC3+RAM+BATTERY"
carttype_map[0x17] = "MBC4+RAM+BATTERY"
carttype_map[0x1B] = "MBC5+RAM+BATTERY"
carttype_map[0x1E] = "MBC5+RUMBLE+RAM+BATTERY"
carttype_map[0xFE] = "HuC3"
carttype_map[0x01] = "MBC1"
carttype_map[0x05] = "MBC2"
carttype_map[0x09] = "ROM+RAM+BATTERY"
carttype_map[0x0D] = "MMM01+RAM+BATTERY"
carttype_map[0x11] = "MBC3"
carttype_map[0x15] = "MBC4"
carttype_map[0x19] = "MBC5"
carttype_map[0x1C] = "MBC5+RUMBLE"
carttype_map[0xFC] = "POCKET CAMERA"
carttype_map[0xFF] = "HuC1+RAM+BATTERY"
carttype_map[0x02] = "MBC1+RAM"
carttype_map[0x06] = "MBC2+BATTERY"
carttype_map[0x0B] = "MMM01"
carttype_map[0x0F] = "MBC3+TIMER+BATTERY"
carttype_map[0x12] = "MBC3+RAM"
carttype_map[0x16] = "MBC4+RAM"
carttype_map[0x1A] = "MBC5+RAM"
carttype_map[0x1D] = "MBC5+RUMBLE+RAM"
carttype_map[0xFD] = "Bandai TAMA5"

license_map = {}
license_map["00"] = "none"
license_map["09"] = "hot-b"
license_map["0C"] = "elite systems"
license_map["19"] = "itc entertainment"
license_map["1F"] = "virgin"
license_map["25"] = "san-x"
license_map["30"] = "infogrames"
license_map["33"] = "GBC - see above"
license_map["38"] = "Capcom"
license_map["3E"] = "gremlin"
license_map["44"] = "Malibu"
license_map["49"] = "irem"
license_map["4F"] = "u.s. gold"
license_map["52"] = "activision"
license_map["55"] = "park place"
license_map["59"] = "milton bradley"
license_map["5C"] = "naxat soft"
license_map["61"] = "virgin"
license_map["6E"] = "elite systems"
license_map["71"] = "Interplay"
license_map["75"] = "the sales curve"
license_map["7A"] = "triffix entertainment"
license_map["80"] = "misawa entertainment"
license_map["8B"] = "bullet-proof software"
license_map["8F"] = "i'max"
license_map["93"] = "tsuburava"
license_map["97"] = "kaneko"
license_map["9B"] = "Tecmo"
license_map["9F"] = "nova"
license_map["A4"] = "Konami"
license_map["A9"] = "technos japan"
license_map["AD"] = "toho"
license_map["B1"] = "ascii or nexoft"
license_map["B6"] = "HAL"
license_map["BA"] = "*culture brain o"
license_map["BF"] = "sammy"
license_map["C3"] = "Squaresoft"
license_map["C6"] = "tonkin house"
license_map["CA"] = "ultra"
license_map["CD"] = "meldac"
license_map["D0"] = "Taito"
license_map["D3"] = "sigma enterprises"
license_map["D7"] = "copya systems"
license_map["DB"] = "ljn"
license_map["DF"] = "altron"
license_map["E2"] = "uutaka"
license_map["E7"] = "athena"
license_map["EA"] = "king records"
license_map["EE"] = "igs"
license_map["FF"] = "ljn"
license_map["01"] = "nintendo"
license_map["0A"] = "jaleco"
license_map["13"] = "electronic arts"
license_map["1A"] = "yanoman"
license_map["20"] = "KSS"
license_map["28"] = "kotobuki systems"
license_map["31"] = "nintendo"
license_map["34"] = "konami"
license_map["39"] = "Banpresto"
license_map["41"] = "Ubisoft"
license_map["46"] = "angel"
license_map["4A"] = "virgin"
license_map["50"] = "absolute"
license_map["53"] = "american sammy"
license_map["56"] = "ljn"
license_map["5A"] = "mindscape"
license_map["5D"] = "tradewest"
license_map["67"] = "ocean"
license_map["6F"] = "electro brain"
license_map["72"] = "broderbund"
license_map["78"] = "t*hq"
license_map["7C"] = "microprose"
license_map["83"] = "lozc"
license_map["8C"] = "vic tokai"
license_map["91"] = "chun soft"
license_map["95"] = "varie"
license_map["99"] = "arc"
license_map["9C"] = "imagineer"
license_map["A1"] = "Hori electric"
license_map["A6"] = "kawada"
license_map["AA"] = "broderbund"
license_map["AF"] = "Namco"
license_map["B2"] = "Bandai"
license_map["B7"] = "SNK"
license_map["BB"] = "Sunsoft"
license_map["C0"] = "Taito"
license_map["C4"] = "tokuma shoten intermedia"
license_map["C8"] = "koei"
license_map["CB"] = "vap"
license_map["CE"] = "*pony canyon or"
license_map["D1"] = "sofel"
license_map["D4"] = "ask kodansha"
license_map["D9"] = "Banpresto"
license_map["DD"] = "ncs"
license_map["E0"] = "jaleco"
license_map["E3"] = "varie"
license_map["E8"] = "asmik"
license_map["EB"] = "atlus"
license_map["F0"] = "a wave"
license_map["08"] = "capcom"
license_map["0B"] = "coconuts"
license_map["18"] = "hudsonsoft"
license_map["1D"] = "clary"
license_map["24"] = "pcm complete"
license_map["29"] = "seta"
license_map["32"] = "bandai"
license_map["35"] = "hector"
license_map["3C"] = "*entertainment i"
license_map["42"] = "Atlus"
license_map["47"] = "spectrum holoby"
license_map["4D"] = "malibu"
license_map["51"] = "acclaim"
license_map["54"] = "gametek"
license_map["57"] = "matchbox"
license_map["5B"] = "romstar"
license_map["60"] = "titus"
license_map["69"] = "electronic arts"
license_map["70"] = "Infogrammes"
license_map["73"] = "sculptered soft"
license_map["79"] = "accolade"
license_map["7F"] = "kemco"
license_map["86"] = "tokuma shoten intermedia"
license_map["8E"] = "ape"
license_map["92"] = "video system"
license_map["96"] = "yonezawa/s'pal"
license_map["9A"] = "nihon bussan"
license_map["9D"] = "Banpresto"
license_map["A2"] = "Bandai"
license_map["A7"] = "takara"
license_map["AC"] = "Toei animation"
license_map["B0"] = "Acclaim"
license_map["B4"] = "Enix"
license_map["B9"] = "pony canyon"
license_map["BD"] = "Sony imagesoft"
license_map["C2"] = "Kemco"
license_map["C5"] = "data east"
license_map["C9"] = "ufl"
license_map["CC"] = "use"
license_map["CF"] = "angel"
license_map["D2"] = "quest"
license_map["D6"] = "naxat soft"
license_map["DA"] = "tomy"
license_map["DE"] = "human"
license_map["E1"] = "towachiki"
license_map["E5"] = "epoch"
license_map["E9"] = "natsume"
license_map["EC"] = "Epic/Sony records"
license_map["F3"] = "extreme entertainment"